### ISSUE TITLE
Confusion with using predict for BMS

### ISSUE THREAD

**Issue by TheLemonPig** [AutoResearch/autora#224]
It is not clear why this error occurred. It has never occurred before to my understanding.

Traceback (most recent call last):
  File "/Users/joshuahewson/Developer/autora/studies/cogsci2020a/run_closed_loop_recovery.py", line 97, in <module>
    # get new experiment conditions
  File "/Users/joshuahewson/Developer/autora/autora/experimentalist/pipeline.py", line 158, in __call__
    results = [pool(**all_params_for_pool)]
  File "/Users/joshuahewson/Developer/autora/autora/experimentalist/pooler/poppernet.py", line 103, in poppernet_pool
    model_prediction = model_predict(x_train)
  File "/Users/joshuahewson/Developer/autora/autora/theorist/bms/mcmc.py", line 1345, in predict
    xmat = [this_x[ds][v.name] for v in variables]
  File "/Users/joshuahewson/Developer/autora/autora/theorist/bms/mcmc.py", line 1345, in <listcomp>
    xmat = [this_x[ds][v.name] for v in variables]
  File "/Users/joshuahewson/Library/Caches/pypoetry/virtualenvs/autora-7pIKBzZh-py3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/joshuahewson/Library/Caches/pypoetry/virtualenvs/autora-7pIKBzZh-py3.8/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    raise KeyError(key) from err
KeyError: 'x'

**Comment by TheLemonPig** [comment]
I understand the problem. It is because BMS has multiple attributes named ```predict```
The one we want the user to use:
- ```bms.predict```
The one we want only bms to use:
- ```bms.model_.predict```

**Comment by TheLemonPig** [comment]
Turns out this is not the case. The error occurs because the experimentalists take in the model instead of the theorist.
